/**
 * The golden corpus: real legacy documents converted and compared against
 * Unicode produced independently of this engine.
 *
 * The corpus is empty today — the samples are coming from the maintainer —
 * so the per-document block skips. The harness itself is tested regardless,
 * against synthetic fixtures written to a temporary directory: a runner that
 * first executes on the day the real documents arrive is a runner nobody has
 * ever seen work, and the day it fails you cannot tell whether the document
 * or the harness is at fault.
 *
 * See `golden/README.md` for the file convention and for why the expected
 * output must not be generated by running this engine.
 */
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { convertLegacyText } from "../engine/pipeline";
import { getEncoding } from "../encodings/registry";
import {
  describeFirstDifference,
  discoverGoldenCases,
  normalizeFixtureText,
  readFixture,
} from "./goldenCorpus";

const GOLDEN_DIR = path.join(__dirname, "golden");
const { cases, unpaired } = discoverGoldenCases(GOLDEN_DIR);

// ---------------------------------------------------------------------------
// The corpus
// ---------------------------------------------------------------------------

describe("golden corpus", () => {
  it("has no legacy file without an expected file", () => {
    // Not a skip: a document added and forgotten must not look like a pass.
    expect(unpaired, "each <name>.<encoding>.legacy.txt needs a matching .expected.txt").toStrictEqual(
      [],
    );
  });

  it.runIf(cases.length === 0)("is empty, so the per-document checks below are skipped", () => {
    // Deliberately a passing test rather than silence, so the suite output
    // says the corpus is empty instead of implying it passed.
    expect(cases).toHaveLength(0);
  });

  describe.skipIf(cases.length === 0)("documents", () => {
    for (const goldenCase of cases) {
      describe(goldenCase.name, () => {
        it("names a registered encoding", () => {
          expect(getEncoding(goldenCase.encodingId), `unknown encoding "${goldenCase.encodingId}"`).toBeDefined();
        });

        it("converts with no unmapped sequence and exactly the expected output", () => {
          const legacy = readFixture(goldenCase.legacyPath);
          const expected = readFixture(goldenCase.expectedPath);

          const result = convertLegacyText(legacy, goldenCase.encodingId);
          expect(result.ok, result.ok ? "" : result.error.message).toBe(true);
          if (!result.ok) return;

          // Reported before the text comparison: an unmapped sequence is the
          // actionable finding, and the output mismatch it causes is noise
          // on top of it.
          expect(
            result.value.validation.unmappedSequences,
            "a real document with an unmapped sequence means a missing mapping rule",
          ).toStrictEqual([]);

          const actual = normalizeFixtureText(result.value.unicodeText);
          expect(actual, describeFirstDifference(actual, expected)).toBe(expected);
        });
      });
    }
  });
});

// ---------------------------------------------------------------------------
// The harness, proven against synthetic fixtures
// ---------------------------------------------------------------------------

const tempDirs: string[] = [];

function makeCorpus(files: Record<string, string>): string {
  const dir = mkdtempSync(path.join(os.tmpdir(), "golden-"));
  tempDirs.push(dir);
  for (const [name, contents] of Object.entries(files)) {
    writeFileSync(path.join(dir, name), contents, "utf8");
  }
  return dir;
}

afterAll(() => {
  for (const dir of tempDirs) rmSync(dir, { recursive: true, force: true });
});

describe("discoverGoldenCases", () => {
  it("finds nothing in an empty directory, without throwing", () => {
    expect(discoverGoldenCases(makeCorpus({}))).toStrictEqual({ cases: [], unpaired: [] });
  });

  it("returns empty for a directory that does not exist", () => {
    const missing = path.join(os.tmpdir(), "golden-does-not-exist-9f3a");
    expect(discoverGoldenCases(missing)).toStrictEqual({ cases: [], unpaired: [] });
  });

  it("pairs a legacy file with its expected file and reads the encoding from the name", () => {
    const dir = makeCorpus({
      "report.bijoy.legacy.txt": "Avwg",
      "report.bijoy.expected.txt": "আমি",
    });
    const { cases: found, unpaired: missing } = discoverGoldenCases(dir);

    expect(missing).toStrictEqual([]);
    expect(found).toHaveLength(1);
    expect(found[0].name).toBe("report.bijoy");
    expect(found[0].encodingId).toBe("bijoy");
  });

  it("reports a legacy file with no expected file instead of skipping it", () => {
    const dir = makeCorpus({ "orphan.bijoy.legacy.txt": "Avwg" });
    const { cases: found, unpaired: missing } = discoverGoldenCases(dir);

    expect(found).toStrictEqual([]);
    expect(missing).toStrictEqual(["orphan.bijoy.legacy.txt"]);
  });

  it("ignores unrelated files, including the README", () => {
    const dir = makeCorpus({
      "README.md": "# notes",
      "notes.txt": "scratch",
      "report.bijoy.legacy.txt": "Avwg",
      "report.bijoy.expected.txt": "আমি",
    });
    expect(discoverGoldenCases(dir).cases).toHaveLength(1);
  });

  it("handles several documents and several encodings", () => {
    const dir = makeCorpus({
      "a.bijoy.legacy.txt": "x",
      "a.bijoy.expected.txt": "y",
      "b.sutonny.legacy.txt": "x",
      "b.sutonny.expected.txt": "y",
    });
    const found = discoverGoldenCases(dir).cases;
    expect(found.map((item) => item.encodingId)).toStrictEqual(["bijoy", "sutonny"]);
  });

  it("does not descend into subdirectories", () => {
    const dir = makeCorpus({ "top.bijoy.legacy.txt": "x", "top.bijoy.expected.txt": "y" });
    mkdirSync(path.join(dir, "nested"));
    writeFileSync(path.join(dir, "nested", "inner.bijoy.legacy.txt"), "x", "utf8");

    expect(discoverGoldenCases(dir).cases).toHaveLength(1);
  });
});

describe("normalizeFixtureText", () => {
  it("strips a BOM", () => {
    expect(normalizeFixtureText("﻿আমি")).toBe("আমি");
  });

  it("normalizes CRLF and one trailing newline", () => {
    expect(normalizeFixtureText("এক\r\nদুই\n")).toBe("এক\nদুই");
  });

  it("keeps leading and interior whitespace exactly", () => {
    // A corpus that trimmed whitespace could not catch a reorder bug that
    // moves a joiner, which is invisible and adjacent to a space.
    expect(normalizeFixtureText("  আ  ি  ")).toBe("  আ  ি  ");
  });

  it("keeps a second trailing newline, because that is content", () => {
    expect(normalizeFixtureText("আমি\n\n")).toBe("আমি\n");
  });

  it("keeps zero-width joiners", () => {
    expect(normalizeFixtureText("ক‍ষ")).toBe("ক‍ষ");
  });
});

describe("describeFirstDifference", () => {
  it("says so when the strings match", () => {
    expect(describeFirstDifference("আমি", "আমি")).toBe("identical");
  });

  it("points at the index where they diverge", () => {
    const message = describeFirstDifference("আমরা", "আমি");
    expect(message).toContain("first difference at index 2");
    expect(message).toContain("expected:");
    expect(message).toContain("actual:");
  });

  it("names the code point, which is the only way to see an invisible character", () => {
    const message = describeFirstDifference("ক‌ষ", "ক‍ষ");
    expect(message).toContain("U+200C");
    expect(message).toContain("U+200D");
  });

  it("handles one string being a prefix of the other", () => {
    expect(describeFirstDifference("আম", "আমি")).toContain("first difference at index 2");
  });
});

describe("the harness end to end, on a synthetic pair", () => {
  it("passes a document whose conversion matches its expected output", () => {
    // Round-tripped through the engine deliberately: this case is about the
    // harness plumbing, not about whether the engine is right. Real cases
    // must never be built this way — see golden/README.md.
    const legacy = "Avwg";
    const converted = convertLegacyText(legacy, "bijoy");
    expect(converted.ok).toBe(true);
    if (!converted.ok) return;

    const dir = makeCorpus({
      "synthetic.bijoy.legacy.txt": legacy,
      "synthetic.bijoy.expected.txt": `${converted.value.unicodeText}\n`,
    });

    const [found] = discoverGoldenCases(dir).cases;
    const result = convertLegacyText(readFixture(found.legacyPath), found.encodingId);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(normalizeFixtureText(result.value.unicodeText)).toBe(readFixture(found.expectedPath));
  });

  it("fails a document whose expected output is wrong, proving the check is not vacuous", () => {
    const dir = makeCorpus({
      "wrong.bijoy.legacy.txt": "Avwg",
      "wrong.bijoy.expected.txt": "this is not the conversion",
    });

    const [found] = discoverGoldenCases(dir).cases;
    const result = convertLegacyText(readFixture(found.legacyPath), found.encodingId);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(normalizeFixtureText(result.value.unicodeText)).not.toBe(readFixture(found.expectedPath));
  });
});
