// Copies the self-hosted runtime the /ocr page needs from the npm packages into public/ocr/:
//   worker.min.js             the Tesseract web worker            (tesseract.js)
//   core/*-lstm.wasm.js       the WASM engine, three CPU variants  (tesseract.js-core)
//   lang/{ben,eng}.traineddata.gz   integer-quantised `best_int` models (@tesseract.js-data/*)
//   pdf.worker.min.mjs        the pdf.js worker                    (pdfjs-dist)
//   pdfjs/{wasm,cmaps,standard_fonts,iccs}/   pdf.js image decoders (JBIG2, JPEG 2000, ICC) and
//                             fonts/CMaps for non-embedded fonts   (pdfjs-dist)
// Tesseract's default is to fetch all of this from a CDN at runtime; hosting it ourselves keeps the
// page working offline after first load, lets the CSP stay `'self'`, and means no third party sees
// which files a visitor reads. Float `best` models are deliberately not used: they crash the WASM
// core (docs/ocr-extraction-plan.md §11).
//
// public/ocr/ is gitignored (~19 MB of binaries) and rebuilt by `predev`/`prebuild`, which only copy
// a file that is missing or a different size, so a repeat run is instant. Run by hand after bumping
// any of the packages above:
//   npm run ocr:sync
import { copyFileSync, existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const out = path.join(root, "public", "ocr");
const nm = (...parts) => path.join(root, "node_modules", ...parts);

const CORE_VARIANTS = [
  "tesseract-core-lstm.wasm.js",
  "tesseract-core-simd-lstm.wasm.js",
  "tesseract-core-relaxedsimd-lstm.wasm.js",
];
const LANGUAGES = ["ben", "eng"];

const PDFJS_DIRS = ["wasm", "cmaps", "standard_fonts", "iccs"];

/** Every file under a directory, as paths relative to it. */
function listFiles(dir, prefix = "") {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? listFiles(path.join(dir, entry.name), path.join(prefix, entry.name))
      : [path.join(prefix, entry.name)],
  );
}

const pdfjsFiles = PDFJS_DIRS.flatMap((dir) => {
  const src = nm("pdfjs-dist", dir);
  if (!existsSync(src)) {
    console.error(`ocr:sync: missing ${path.relative(root, src)} — run \`npm install\` first.`);
    process.exit(1);
  }
  return listFiles(src).map((rel) => ({
    from: path.join(src, rel),
    to: path.join(out, "pdfjs", dir, rel),
  }));
});

const files = [
  { from: nm("tesseract.js", "dist", "worker.min.js"), to: path.join(out, "worker.min.js") },
  ...CORE_VARIANTS.map((name) => ({
    from: nm("tesseract.js-core", name),
    to: path.join(out, "core", name),
  })),
  ...LANGUAGES.map((lang) => ({
    from: nm("@tesseract.js-data", lang, "4.0.0_best_int", `${lang}.traineddata.gz`),
    to: path.join(out, "lang", `${lang}.traineddata.gz`),
  })),
  { from: nm("pdfjs-dist", "build", "pdf.worker.min.mjs"), to: path.join(out, "pdf.worker.min.mjs") },
  ...pdfjsFiles,
];

let copied = 0;
for (const { from, to } of files) {
  if (!existsSync(from)) {
    console.error(`ocr:sync: missing ${path.relative(root, from)} — run \`npm install\` first.`);
    process.exit(1);
  }
  if (existsSync(to) && statSync(to).size === statSync(from).size) continue;
  mkdirSync(path.dirname(to), { recursive: true });
  copyFileSync(from, to);
  copied++;
}

mkdirSync(out, { recursive: true });
writeFileSync(
  path.join(out, "NOTICE.txt"),
  [
    "Third-party files served for the /ocr page. Generated by `npm run ocr:sync`.",
    "",
    "worker.min.js, core/*      tesseract.js and tesseract.js-core — Apache-2.0",
    "lang/*.traineddata.gz      tessdata_best (integer-quantised), Apache-2.0, packaged by @tesseract.js-data (MIT)",
    "pdf.worker.min.mjs, pdfjs/*  pdf.js — Apache-2.0",
    "",
  ].join("\n"),
);

console.log(
  copied === 0
    ? "ocr:sync: public/ocr/ already up to date"
    : `ocr:sync: copied ${copied} file(s) -> public/ocr/`,
);
