// Copies the self-hosted runtime the /ocr page needs from the npm packages into public/ocr/:
//   worker.min.js             the Tesseract web worker            (tesseract.js)
//   core/*-lstm.wasm.js       the WASM engine, three CPU variants  (tesseract.js-core)
//   lang/{ben,eng}.traineddata.gz   integer-quantised `best_int` models (@tesseract.js-data/*)
//   pdf.worker.min.mjs        the pdf.js worker                    (pdfjs-dist)
// Tesseract's default is to fetch all of this from a CDN at runtime; hosting it ourselves keeps the
// page working offline after first load, lets the CSP stay `'self'`, and means no third party sees
// which files a visitor reads. Float `best` models are deliberately not used: they crash the WASM
// core (docs/ocr-extraction-plan.md §11).
//
// public/ocr/ is gitignored (~15 MB of binaries) and rebuilt by `predev`/`prebuild`, which only copy
// a file that is missing or a different size, so a repeat run is instant. Run by hand after bumping
// any of the packages above:
//   npm run ocr:sync
import { copyFileSync, existsSync, mkdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const out = path.join(root, "public", "ocr");
const nm = (...parts) => path.join(root, "node_modules", ...parts);

const CORE_VARIANTS = [
  "tesseract-core-lstm.wasm.js",
  "tesseract-core-simd-lstm.wasm.js",
  "tesseract-core-relaxedsimd-lstm.wasm.js",
];
const LANGUAGES = ["ben", "eng"];

const files = [
  { from: nm("tesseract.js", "dist", "worker.min.js"), to: path.join(out, "worker.min.js") },
  ...CORE_VARIANTS.map((name) => ({
    from: nm("tesseract.js-core", name),
    to: path.join(out, "core", name),
  })),
  ...LANGUAGES.map((lang) => ({
    from: nm("@tesseract.js-data", lang, "4.0.0_best_int", `${lang}.traineddata.gz`),
    to: path.join(out, "lang", `${lang}.traineddata.gz`),
  })),
  { from: nm("pdfjs-dist", "build", "pdf.worker.min.mjs"), to: path.join(out, "pdf.worker.min.mjs") },
];

let copied = 0;
for (const { from, to } of files) {
  if (!existsSync(from)) {
    console.error(`ocr:sync: missing ${path.relative(root, from)} — run \`npm install\` first.`);
    process.exit(1);
  }
  if (existsSync(to) && statSync(to).size === statSync(from).size) continue;
  mkdirSync(path.dirname(to), { recursive: true });
  copyFileSync(from, to);
  copied++;
}

mkdirSync(out, { recursive: true });
writeFileSync(
  path.join(out, "NOTICE.txt"),
  [
    "Third-party files served for the /ocr page. Generated by `npm run ocr:sync`.",
    "",
    "worker.min.js, core/*      tesseract.js and tesseract.js-core — Apache-2.0",
    "lang/*.traineddata.gz      tessdata_best (integer-quantised), Apache-2.0, packaged by @tesseract.js-data (MIT)",
    "pdf.worker.min.mjs         pdf.js — Apache-2.0",
    "",
  ].join("\n"),
);

console.log(
  copied === 0
    ? "ocr:sync: public/ocr/ already up to date"
    : `ocr:sync: copied ${copied} file(s) -> public/ocr/`,
);
